name: bescreen_full_polarsltscpu
channels:
  - conda-forge
  - bioconda
dependencies:
  - polars-lts-cpu
  - pandas
  - pyarrow
  - pyfaidx
  - pyranges
  - ensembl-vep
  # - scipy
  - blast
  - pysam
